"""
Configuration management for FloorballStatsTracker
"""
import os
from datetime import timedelta
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Security: Force FLOORBALL_PIN environment variable (no default allowed)
REQUIRED_PIN = os.environ.get('FLOORBALL_PIN')
if not REQUIRED_PIN:
    raise ValueError("FLOORBALL_PIN environment variable must be set. No default allowed for security.")
if len(REQUIRED_PIN) < 6:
    raise ValueError("FLOORBALL_PIN must be at least 6 characters for security.")

# Security: Force secret key to be set and prevent dev_secret in production
SECRET_KEY = os.environ.get('FLASK_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("FLASK_SECRET_KEY environment variable must be set")
if SECRET_KEY == 'dev_secret':
    raise ValueError("FLASK_SECRET_KEY cannot be 'dev_secret' in production")

# File paths
GAMES_FILE = 'gamesFiles/games.json'
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ROSTERS_DIR = os.path.join(BASE_DIR, 'rosters')

# Ensure directories exist
if not os.path.exists(ROSTERS_DIR):
    os.makedirs(ROSTERS_DIR)

# Ensure games.json exists
if not os.path.exists(GAMES_FILE):
    import json
    with open(GAMES_FILE, 'w') as f:
        json.dump([], f)

# Game constants
CATEGORIES = ['U18', 'U21', 'U16', 'Senior']
PERIODS = ["1", "2", "3", "OT"]

# Flask configuration
FLASK_CONFIG = {
    'SECRET_KEY': SECRET_KEY,
    'WTF_CSRF_ENABLED': True,
    'WTF_CSRF_TIME_LIMIT': None,
    'SESSION_COOKIE_SECURE': os.environ.get('SESSION_COOKIE_SECURE', 'True').lower() == 'true',
    'SESSION_COOKIE_HTTPONLY': True,
    'SESSION_COOKIE_SAMESITE': 'Lax',
    'PERMANENT_SESSION_LIFETIME': timedelta(hours=2),
    'DEFAULT_LANG': os.environ.get('DEFAULT_LANG', 'en'),
}

# Language support
LANGUAGES = ['en', 'it']
TRANSLATIONS = {
    'en': {
        'brand': 'Floorball Stats',
        'enter_access_pin': 'Enter Access PIN',
        'pin_placeholder': 'Enter PIN',
        'enter': 'Enter',
        'lang_en': 'English',
        'lang_it': 'Italian',
        'change': 'Change',
        'create_game': 'Create Game',
        'stats': 'Statistics',
        'create_new_game': 'Create New Game',
        'all_teams': 'All Teams',
        'go_to_latest_game': 'Go to Latest Game',
        'stats_btn': 'Stats',
        'title': 'Floorball Stats Tracker',
        'all_games': 'All Games',
        'all_games_for': 'All Games for',
        'view': 'View',
        'no_games': 'No games found. Create a new game to get started!',
        'back_to_home': 'Back to Home',
        'modify_game': 'Modify Game',
        'reset_stats': 'Reset Stats',
        'confirm_reset_title': 'Confirm Reset',
        'confirm_reset_body': 'Are you sure you want to reset all stats for this game?',
        'confirm_reset_cancel': 'Cancel',
        'confirm_reset_confirm': 'Reset',
        'edit_mode': 'Edit Mode',
        'switch_game': 'Switch game',
        'line': 'Line',
        'player': 'Player',
        'plusminus': '+/-',
        'goals': 'Goals',
        'assists': 'Assists',
        'errors': 'Errors',
        'sog': 'SOG',
        'penalties_drawn': 'P. Drawn',
        'penalties_taken': 'P. Taken',
        'game_score': 'GS',
        'home': 'Home',
        'away': 'Away',
        'date': 'Date',
        'referee': 'Referee',
        'season': 'Season',
        'team': 'Team',
        'home_team': 'Home Team',
        'away_team': 'Away Team',
        'create': 'Create',
        'save': 'Save',
        'delete': 'Delete',
        'edit': 'Edit',
        'back': 'Back',
        'period': 'Period',
        'goalie': 'Goalie',
        'saves': 'Saves',
        'goals_conceded': 'Goals Conceded',
        'save_percentage': 'Save %',
        'opponent_goalie': 'Opponent Goalie',
        'enable_opponent_goalie_tracking': 'Enable Opponent Goalie Tracking',
        'roster': 'Roster',
        'add_player': 'Add Player',
        'bulk_import': 'Bulk Import',
        'number': 'Number',
        'surname': 'Surname',
        'name': 'Name',
        'nickname': 'Nickname',
        'position': 'Position',
        'position_a': 'Attacker',
        'position_c': 'Center',
        'position_d': 'Defender',
        'position_p': 'Goalie',
        'tesser': 'Tesser',
        'select_roster': 'Roster',
        'select_category': 'Select Category',
        'u18': 'U18',
        'u21': 'U21',
        'u21_dp': 'U21 DP',
        'u16': 'U16',
        'no_players': 'No players in the roster. Add players to get started!',
        'formations': 'Formations',
        'pp1': 'PP1',
        'pp2': 'PP2',
        'bp1': 'BP1',
        'bp2': 'BP2',
        '6vs5': '6vs5',
        'stress_line': 'Stress Line',
        'convocato': 'Called Up',
        'summary': 'Summary',
        'by_position': 'By Position',
        'by_category': 'By Category',
        'use_for_game': 'Use for Game',
        'bulk_import_title': 'Bulk Import Players',
        'bulk_import_instructions': 'Paste player data below (one player per line). Format: Number, Surname, Name, Position, Tesser, Nickname',
        'bulk_import_example': 'Example: 10, Smith, John, A, U18, Johnny',
        'bulk_import_format': 'Supported formats: Tab-separated (from Excel/Sheets) or comma-separated',
        'bulk_data': 'Player Data',
        'import_players': 'Import Players',
        'or_manual': 'Or add manually',
        'starting_goalies': 'Starting Goalies',
        'first_goalie': 'Starting Goalie',
        'second_goalie': 'Backup Goalie',
        'lineup': 'Full Lineup',
        'select_goalie': 'Select Goalie',
        'select_starting_goalie': 'Select Starting Goalie',
        'select_starting_goalie_instruction': 'Select goalies in the roster above, then choose who starts',
        'hide_inactive_players': 'Hide players without number',
        'select_category': 'Select Category',
        'error_loading_roster': 'Error loading roster for this category',
        'plusminus_rules_title': 'Plus/Minus Rules',
        'plusminus_rules_text': 'A player receives +1 for every even-strength or shorthanded goal scored by their team while on the ice, and -1 for every similar goal scored by the opposing team. Power-play goals and penalty shots do not affect plus/minus. Goalies do not have a plus/minus rating.',
    },
    'it': {
        'brand': 'Floorball Stats',
        'enter_access_pin': 'Inserisci PIN di Accesso',
        'pin_placeholder': 'Inserisci PIN',
        'enter': 'Entra',
        'lang_en': 'Inglese',
        'lang_it': 'Italiano',
        'change': 'Cambia',
        'create_game': 'Crea Partita',
        'stats': 'Statistiche',
        'create_new_game': 'Crea Nuova Partita',
        'all_teams': 'Tutte le Squadre',
        'go_to_latest_game': 'Vai all\'Ultima Partita',
        'stats_btn': 'Statistiche',
        'title': 'Floorball Stats Tracker',
        'all_games': 'Tutte le Partite',
        'all_games_for': 'Tutte le Partite per',
        'view': 'Visualizza',
        'no_games': 'Nessuna partita trovata. Crea una nuova partita per iniziare!',
        'back_to_home': 'Torna alla Home',
        'modify_game': 'Modifica Partita',
        'reset_stats': 'Resetta Statistiche',
        'confirm_reset_title': 'Conferma Reset',
        'confirm_reset_body': 'Sei sicuro di voler resettare tutte le statistiche per questa partita?',
        'confirm_reset_cancel': 'Annulla',
        'confirm_reset_confirm': 'Resetta',
        'edit_mode': 'Modalità Modifica',
        'switch_game': 'Cambia partita',
        'line': 'Linea',
        'player': 'Giocatore',
        'plusminus': '+/-',
        'goals': 'Goal',
        'assists': 'Assist',
        'errors': 'Errori',
        'sog': 'Tiri',
        'penalties_drawn': 'P. Subite',
        'penalties_taken': 'P. Prese',
        'game_score': 'GS',
        'home': 'Casa',
        'away': 'Trasferta',
        'date': 'Data',
        'referee': 'Arbitro',
        'season': 'Stagione',
        'team': 'Squadra',
        'home_team': 'Squadra Casa',
        'away_team': 'Squadra Trasferta',
        'create': 'Crea',
        'save': 'Salva',
        'delete': 'Elimina',
        'edit': 'Modifica',
        'back': 'Indietro',
        'period': 'Periodo',
        'goalie': 'Portiere',
        'saves': 'Parate',
        'goals_conceded': 'Goal Subiti',
        'save_percentage': 'Parate %',
        'opponent_goalie': 'Portiere Avversario',
        'enable_opponent_goalie_tracking': 'Abilita Tracking Portiere Avversario',
        'roster': 'Rosa',
        'add_player': 'Aggiungi Giocatore',
        'bulk_import': 'Importazione Massiva',
        'number': 'Numero',
        'surname': 'Cognome',
        'name': 'Nome',
        'nickname': 'Soprannome',
        'position': 'Posizione',
        'position_a': 'Attaccante',
        'position_c': 'Centro',
        'position_d': 'Difensore',
        'position_p': 'Portiere',
        'tesser': 'Tesser',
        'select_roster': 'Rosa',
        'select_category': 'Seleziona Categoria',
        'u18': 'U18',
        'u21': 'U21',
        'u21_dp': 'U21 DP',
        'u16': 'U16',
        'no_players': 'Nessun giocatore nella rosa. Aggiungi giocatori per iniziare!',
        'formations': 'Formazioni',
        'pp1': 'PP1',
        'pp2': 'PP2',
        'bp1': 'BP1',
        'bp2': 'BP2',
        '6vs5': '6vs5',
        'stress_line': 'Linea Stress',
        'convocato': 'Convocato',
        'summary': 'Riepilogo',
        'by_position': 'Per Posizione',
        'by_category': 'Per Categoria',
        'use_for_game': 'Usa per Partita',
        'bulk_import_title': 'Importazione Massiva Giocatori',
        'bulk_import_instructions': 'Incolla i dati dei giocatori qui sotto (un giocatore per riga). Formato: Numero, Cognome, Nome, Posizione, Tesser, Soprannome',
        'bulk_import_example': 'Esempio: 10, Rossi, Mario, A, U18, Marietto',
        'bulk_import_format': 'Formati supportati: Separati da tabulazione (da Excel/Sheets) o separati da virgola',
        'bulk_data': 'Dati Giocatori',
        'import_players': 'Importa Giocatori',
        'or_manual': 'Oppure inserisci manualmente',
        'starting_goalies': 'Portieri Titolari',
        'first_goalie': 'Portiere Titolare',
        'second_goalie': 'Portiere di Riserva',
        'lineup': 'Formazione Completa',
        'select_goalie': 'Seleziona Portiere',
        'select_starting_goalie': 'Seleziona Portiere Titolare',
        'select_starting_goalie_instruction': 'Seleziona i portieri nel roster sopra, poi scegli chi parte titolare',
        'hide_inactive_players': 'Nascondi giocatori senza numero',
        'select_category': 'Seleziona Categoria',
        'error_loading_roster': 'Errore nel caricamento del roster per questa categoria',
        'plusminus_rules_title': 'Regole Plus/Minus',
        'plusminus_rules_text': 'Un giocatore riceve +1 per ogni gol a squadre pari o in inferiorità numerica segnato dalla propria squadra mentre è in campo, e -1 per ogni gol simile segnato dalla squadra avversaria. I gol in superiorità numerica e i rigori non influenzano il plus/minus. I portieri non hanno una valutazione plus/minus.',
    }
}
